// Mocks generated by Mockito 5.4.6 from annotations
// in musicpod/test/podcast_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:musicpod/common/data/audio.dart' as _i7;
import 'package:musicpod/common/view/languages.dart' as _i6;
import 'package:musicpod/podcasts/data/podcast_genre.dart' as _i4;
import 'package:musicpod/podcasts/podcast_service.dart' as _i3;
import 'package:podcast_search/podcast_search.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSearchProvider_0 extends _i1.SmartFake
    implements _i2.SearchProvider {
  _FakeSearchProvider_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PodcastService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPodcastService extends _i1.Mock implements _i3.PodcastService {
  MockPodcastService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.PodcastGenre> get cachedPodcastGenres =>
      (super.noSuchMethod(
            Invocation.getter(#cachedPodcastGenres),
            returnValue: <_i4.PodcastGenre>[],
          )
          as List<_i4.PodcastGenre>);

  @override
  Set<String> get feedsWithDownloads =>
      (super.noSuchMethod(
            Invocation.getter(#feedsWithDownloads),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  List<String> get podcastFeedUrls =>
      (super.noSuchMethod(
            Invocation.getter(#podcastFeedUrls),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  Set<String> get podcasts =>
      (super.noSuchMethod(Invocation.getter(#podcasts), returnValue: <String>{})
          as Set<String>);

  @override
  int get podcastsLength =>
      (super.noSuchMethod(Invocation.getter(#podcastsLength), returnValue: 0)
          as int);

  @override
  Set<String> get ascendingPodcasts =>
      (super.noSuchMethod(
            Invocation.getter(#ascendingPodcasts),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Set<String> get podcastUpdates =>
      (super.noSuchMethod(
            Invocation.getter(#podcastUpdates),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  set feedsWithDownloads(Set<String>? value) => super.noSuchMethod(
    Invocation.setter(#feedsWithDownloads, value),
    returnValueForMissingStub: null,
  );

  @override
  set podcastUpdates(Set<String>? value) => super.noSuchMethod(
    Invocation.setter(#podcastUpdates, value),
    returnValueForMissingStub: null,
  );

  @override
  _i2.SearchProvider initSearchProvider({bool? forceInit = false}) =>
      (super.noSuchMethod(
            Invocation.method(#initSearchProvider, [], {#forceInit: forceInit}),
            returnValue: _FakeSearchProvider_0(
              this,
              Invocation.method(#initSearchProvider, [], {
                #forceInit: forceInit,
              }),
            ),
          )
          as _i2.SearchProvider);

  @override
  _i5.Future<List<_i4.PodcastGenre>> loadGenres({bool? force = false}) =>
      (super.noSuchMethod(
            Invocation.method(#loadGenres, [], {#force: force}),
            returnValue: _i5.Future<List<_i4.PodcastGenre>>.value(
              <_i4.PodcastGenre>[],
            ),
          )
          as _i5.Future<List<_i4.PodcastGenre>>);

  @override
  _i5.Future<_i2.SearchResult?> search({
    String? searchQuery,
    _i4.PodcastGenre? podcastGenre = _i4.PodcastGenre.all,
    _i2.Country? country,
    _i6.SimpleLanguage? language,
    int? limit = 10,
    _i2.Attribute? attribute = _i2.Attribute.none,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [], {
              #searchQuery: searchQuery,
              #podcastGenre: podcastGenre,
              #country: country,
              #language: language,
              #limit: limit,
              #attribute: attribute,
            }),
            returnValue: _i5.Future<_i2.SearchResult?>.value(),
          )
          as _i5.Future<_i2.SearchResult?>);

  @override
  _i5.Future<Set<String>> checkForUpdates({
    required Iterable<String>? feedUrls,
    void Function(double)? updateProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkForUpdates, [], {
              #feedUrls: feedUrls,
              #updateProgress: updateProgress,
            }),
            returnValue: _i5.Future<Set<String>>.value(<String>{}),
          )
          as _i5.Future<Set<String>>);

  @override
  _i5.Future<List<_i7.Audio>> findEpisodes({
    required String? feedUrl,
    required bool? tryFromDbOnly,
    String? genre,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findEpisodes, [], {
              #feedUrl: feedUrl,
              #tryFromDbOnly: tryFromDbOnly,
              #genre: genre,
            }),
            returnValue: _i5.Future<List<_i7.Audio>>.value(<_i7.Audio>[]),
          )
          as _i5.Future<List<_i7.Audio>>);

  @override
  _i5.Future<void> loadDownloads() =>
      (super.noSuchMethod(
            Invocation.method(#loadDownloads, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addDownload({
    required String? url,
    required String? path,
    required String? feedUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addDownload, [], {
              #url: url,
              #path: path,
              #feedUrl: feedUrl,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeDownload({
    required String? url,
    required String? feedUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeDownload, [], {
              #url: url,
              #feedUrl: feedUrl,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeAllDownloads() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllDownloads, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isPodcastSubscribed(String? pageId) =>
      (super.noSuchMethod(
            Invocation.method(#isPodcastSubscribed, [pageId]),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<void> loadPodcasts() =>
      (super.noSuchMethod(
            Invocation.method(#loadPodcasts, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  String? getSubscribedPodcastImage(String? feedUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getSubscribedPodcastImage, [feedUrl]),
          )
          as String?);

  @override
  void addPodcastImage({
    required String? feedUrl,
    required String? imageUrl,
    required String? title,
  }) => super.noSuchMethod(
    Invocation.method(#addPodcastImage, [], {
      #feedUrl: feedUrl,
      #imageUrl: imageUrl,
      #title: title,
    }),
    returnValueForMissingStub: null,
  );

  @override
  String? getPodcastName(String? feedUrl) =>
      (super.noSuchMethod(Invocation.method(#getPodcastName, [feedUrl]))
          as String?);

  @override
  String? getSubscribedPodcastArtist(String? feedUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getSubscribedPodcastArtist, [feedUrl]),
          )
          as String?);

  @override
  _i5.Future<void> addPodcast({
    required String? feedUrl,
    required String? imageUrl,
    required String? name,
    required String? artist,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addPodcast, [], {
              #feedUrl: feedUrl,
              #imageUrl: imageUrl,
              #name: name,
              #artist: artist,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addPodcasts(
    List<({String artist, String feedUrl, String? imageUrl, String name})>?
    podcasts,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addPodcasts, [podcasts]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> reorderPodcast({
    required String? feedUrl,
    required bool? ascending,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reorderPodcast, [], {
              #feedUrl: feedUrl,
              #ascending: ascending,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> loadPodcastUpdates() =>
      (super.noSuchMethod(
            Invocation.method(#loadPodcastUpdates, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  String? getPodcastLastUpdated(String? feedUrl) =>
      (super.noSuchMethod(Invocation.method(#getPodcastLastUpdated, [feedUrl]))
          as String?);

  @override
  bool podcastUpdateAvailable(String? feedUrl) =>
      (super.noSuchMethod(
            Invocation.method(#podcastUpdateAvailable, [feedUrl]),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<void> removePodcastUpdates({
    Iterable<String>? feedUrls,
    required void Function(double)? updateProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removePodcastUpdates, [], {
              #feedUrls: feedUrls,
              #updateProgress: updateProgress,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removePodcastUpdate(String? feedUrl) =>
      (super.noSuchMethod(
            Invocation.method(#removePodcastUpdate, [feedUrl]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removePodcastsWithUpdatesAndEpisodes(String? feedUrl) =>
      (super.noSuchMethod(
            Invocation.method(#removePodcastsWithUpdatesAndEpisodes, [feedUrl]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Set<String>> deleteOrphanEpisodes() =>
      (super.noSuchMethod(
            Invocation.method(#deleteOrphanEpisodes, []),
            returnValue: _i5.Future<Set<String>>.value(<String>{}),
          )
          as _i5.Future<Set<String>>);

  @override
  _i5.Future<void> updateAudioDuration(_i7.Audio? audio) =>
      (super.noSuchMethod(
            Invocation.method(#updateAudioDuration, [audio]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> wipeAndBuildPodcastLibrary() =>
      (super.noSuchMethod(
            Invocation.method(#wipeAndBuildPodcastLibrary, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> findPodcastGenre(String? feedUrl) =>
      (super.noSuchMethod(
            Invocation.method(#findPodcastGenre, [feedUrl]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> addPodcastGenre({
    required String? feedUrl,
    required String? genreName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addPodcastGenre, [], {
              #feedUrl: feedUrl,
              #genreName: genreName,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
