// Mocks generated by Mockito 5.4.6 from annotations
// in musicpod/test/podcast_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:musicpod/common/data/audio.dart' as _i3;
import 'package:musicpod/common/persistence/database.dart' as _i9;
import 'package:musicpod/common/view/languages.dart' as _i7;
import 'package:musicpod/podcasts/data/podcast_genre.dart' as _i5;
import 'package:musicpod/podcasts/podcast_service.dart' as _i4;
import 'package:podcast_search/podcast_search.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSearchProvider_0 extends _i1.SmartFake
    implements _i2.SearchProvider {
  _FakeSearchProvider_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAudio_1 extends _i1.SmartFake implements _i3.Audio {
  _FakeAudio_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PodcastService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPodcastService extends _i1.Mock implements _i4.PodcastService {
  MockPodcastService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.PodcastGenre> get cachedPodcastGenres =>
      (super.noSuchMethod(
            Invocation.getter(#cachedPodcastGenres),
            returnValue: <_i5.PodcastGenre>[],
          )
          as List<_i5.PodcastGenre>);

  @override
  Map<String, String> get downloadedFilePaths =>
      (super.noSuchMethod(
            Invocation.getter(#downloadedFilePaths),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  Set<String> get feedsWithDownloads =>
      (super.noSuchMethod(
            Invocation.getter(#feedsWithDownloads),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  List<String> get podcastFeedUrls =>
      (super.noSuchMethod(
            Invocation.getter(#podcastFeedUrls),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  Set<String> get podcasts =>
      (super.noSuchMethod(Invocation.getter(#podcasts), returnValue: <String>{})
          as Set<String>);

  @override
  int get podcastsLength =>
      (super.noSuchMethod(Invocation.getter(#podcastsLength), returnValue: 0)
          as int);

  @override
  Set<String> get ascendingPodcasts =>
      (super.noSuchMethod(
            Invocation.getter(#ascendingPodcasts),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Set<String> get podcastUpdates =>
      (super.noSuchMethod(
            Invocation.getter(#podcastUpdates),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  set feedsWithDownloads(Set<String>? value) => super.noSuchMethod(
    Invocation.setter(#feedsWithDownloads, value),
    returnValueForMissingStub: null,
  );

  @override
  set podcastUpdates(Set<String>? value) => super.noSuchMethod(
    Invocation.setter(#podcastUpdates, value),
    returnValueForMissingStub: null,
  );

  @override
  _i2.SearchProvider initSearchProvider({bool? forceInit = false}) =>
      (super.noSuchMethod(
            Invocation.method(#initSearchProvider, [], {#forceInit: forceInit}),
            returnValue: _FakeSearchProvider_0(
              this,
              Invocation.method(#initSearchProvider, [], {
                #forceInit: forceInit,
              }),
            ),
          )
          as _i2.SearchProvider);

  @override
  _i6.Future<List<_i5.PodcastGenre>> loadGenres({bool? force = false}) =>
      (super.noSuchMethod(
            Invocation.method(#loadGenres, [], {#force: force}),
            returnValue: _i6.Future<List<_i5.PodcastGenre>>.value(
              <_i5.PodcastGenre>[],
            ),
          )
          as _i6.Future<List<_i5.PodcastGenre>>);

  @override
  _i6.Future<_i2.SearchResult?> search({
    String? searchQuery,
    _i5.PodcastGenre? podcastGenre = _i5.PodcastGenre.all,
    _i2.Country? country,
    _i7.SimpleLanguage? language,
    int? limit = 10,
    _i2.Attribute? attribute = _i2.Attribute.none,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [], {
              #searchQuery: searchQuery,
              #podcastGenre: podcastGenre,
              #country: country,
              #language: language,
              #limit: limit,
              #attribute: attribute,
            }),
            returnValue: _i6.Future<_i2.SearchResult?>.value(),
          )
          as _i6.Future<_i2.SearchResult?>);

  @override
  _i6.Future<Set<String>> checkForUpdates({
    required Iterable<String>? feedUrls,
    void Function(double)? updateProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkForUpdates, [], {
              #feedUrls: feedUrls,
              #updateProgress: updateProgress,
            }),
            returnValue: _i6.Future<Set<String>>.value(<String>{}),
          )
          as _i6.Future<Set<String>>);

  @override
  _i6.Future<List<_i3.Audio>> findEpisodes({
    _i2.Item? item,
    String? feedUrl,
    required bool? tryFromDbOnly,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findEpisodes, [], {
              #item: item,
              #feedUrl: feedUrl,
              #tryFromDbOnly: tryFromDbOnly,
            }),
            returnValue: _i6.Future<List<_i3.Audio>>.value(<_i3.Audio>[]),
          )
          as _i6.Future<List<_i3.Audio>>);

  @override
  _i6.Future<String?> download({
    required _i3.Audio? episode,
    required _i8.CancelToken? cancelToken,
    required void Function(int, int)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#download, [], {
              #episode: episode,
              #cancelToken: cancelToken,
              #onProgress: onProgress,
            }),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> loadDownloadsFromDb() =>
      (super.noSuchMethod(
            Invocation.method(#loadDownloadsFromDb, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> addDownload({
    required String? url,
    required String? path,
    required String? feedUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addDownload, [], {
              #url: url,
              #path: path,
              #feedUrl: feedUrl,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeDownload({
    required String? url,
    required String? feedUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeDownload, [], {
              #url: url,
              #feedUrl: feedUrl,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeAllDownloads() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllDownloads, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeFeedWithDownload(String? feedUrl) =>
      (super.noSuchMethod(
            Invocation.method(#removeFeedWithDownload, [feedUrl]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> loadPodcastCacheFromDb() =>
      (super.noSuchMethod(
            Invocation.method(#loadPodcastCacheFromDb, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  String? getSubscribedPodcastImage(String? feedUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getSubscribedPodcastImage, [feedUrl]),
          )
          as String?);

  @override
  void addSubscribedPodcastImage({
    required String? feedUrl,
    required String? imageUrl,
    required String? title,
  }) => super.noSuchMethod(
    Invocation.method(#addSubscribedPodcastImage, [], {
      #feedUrl: feedUrl,
      #imageUrl: imageUrl,
      #title: title,
    }),
    returnValueForMissingStub: null,
  );

  @override
  String? getSubscribedPodcastName(String? feedUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getSubscribedPodcastName, [feedUrl]),
          )
          as String?);

  @override
  String? getSubscribedPodcastArtist(String? feedUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getSubscribedPodcastArtist, [feedUrl]),
          )
          as String?);

  @override
  _i6.Future<void> addPodcast({
    required String? feedUrl,
    required String? imageUrl,
    required String? name,
    required String? artist,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addPodcast, [], {
              #feedUrl: feedUrl,
              #imageUrl: imageUrl,
              #name: name,
              #artist: artist,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> addPodcasts(
    List<({String artist, String feedUrl, String? imageUrl, String name})>?
    podcasts,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addPodcasts, [podcasts]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> reorderPodcast({
    required String? feedUrl,
    required bool? ascending,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reorderPodcast, [], {
              #feedUrl: feedUrl,
              #ascending: ascending,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> loadPodcastUpdatesFromDb() =>
      (super.noSuchMethod(
            Invocation.method(#loadPodcastUpdatesFromDb, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  String? getPodcastLastUpdated(String? feedUrl) =>
      (super.noSuchMethod(Invocation.method(#getPodcastLastUpdated, [feedUrl]))
          as String?);

  @override
  bool podcastUpdateAvailable(String? feedUrl) =>
      (super.noSuchMethod(
            Invocation.method(#podcastUpdateAvailable, [feedUrl]),
            returnValue: false,
          )
          as bool);

  @override
  _i6.Future<void> removePodcastUpdates({
    Iterable<String>? feedUrls,
    required void Function(double)? updateProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removePodcastUpdates, [], {
              #feedUrls: feedUrls,
              #updateProgress: updateProgress,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removePodcastUpdate(String? feedUrl) =>
      (super.noSuchMethod(
            Invocation.method(#removePodcastUpdate, [feedUrl]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removePodcast(String? feedUrl) =>
      (super.noSuchMethod(
            Invocation.method(#removePodcast, [feedUrl]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeAllPodcasts() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllPodcasts, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> wipeAndBuildPodcastLibrary() =>
      (super.noSuchMethod(
            Invocation.method(#wipeAndBuildPodcastLibrary, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateAudioDuration(_i3.Audio? audio) =>
      (super.noSuchMethod(
            Invocation.method(#updateAudioDuration, [audio]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  bool isPodcastSubscribed(String? pageId) =>
      (super.noSuchMethod(
            Invocation.method(#isPodcastSubscribed, [pageId]),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Audio getEpisodeFromTableEntry(
    _i9.PodcastEpisodeTableData? data, {
    required String? feedUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getEpisodeFromTableEntry,
              [data],
              {#feedUrl: feedUrl},
            ),
            returnValue: _FakeAudio_1(
              this,
              Invocation.method(
                #getEpisodeFromTableEntry,
                [data],
                {#feedUrl: feedUrl},
              ),
            ),
          )
          as _i3.Audio);
}
