// Mocks generated by Mockito 5.4.6 from annotations
// in musicpod/test/radio_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:drift/drift.dart' as _i2;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:musicpod/common/persistence/database.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMigrationStrategy_0 extends _i1.SmartFake
    implements _i2.MigrationStrategy {
  _FakeMigrationStrategy_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$DatabaseManager_1 extends _i1.SmartFake
    implements _i3.$DatabaseManager {
  _Fake$DatabaseManager_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ArtistTableTable_2 extends _i1.SmartFake
    implements _i3.$ArtistTableTable {
  _Fake$ArtistTableTable_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AlbumTableTable_3 extends _i1.SmartFake
    implements _i3.$AlbumTableTable {
  _Fake$AlbumTableTable_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AlbumArtTableTable_4 extends _i1.SmartFake
    implements _i3.$AlbumArtTableTable {
  _Fake$AlbumArtTableTable_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$GenreTableTable_5 extends _i1.SmartFake
    implements _i3.$GenreTableTable {
  _Fake$GenreTableTable_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$TrackTableTable_6 extends _i1.SmartFake
    implements _i3.$TrackTableTable {
  _Fake$TrackTableTable_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$PlaylistTableTable_7 extends _i1.SmartFake
    implements _i3.$PlaylistTableTable {
  _Fake$PlaylistTableTable_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$PlaylistTrackTableTable_8 extends _i1.SmartFake
    implements _i3.$PlaylistTrackTableTable {
  _Fake$PlaylistTrackTableTable_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$LikedTrackTableTable_9 extends _i1.SmartFake
    implements _i3.$LikedTrackTableTable {
  _Fake$LikedTrackTableTable_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$StarredStationTableTable_10 extends _i1.SmartFake
    implements _i3.$StarredStationTableTable {
  _Fake$StarredStationTableTable_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$FavoriteRadioTagTableTable_11 extends _i1.SmartFake
    implements _i3.$FavoriteRadioTagTableTable {
  _Fake$FavoriteRadioTagTableTable_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _Fake$PodcastTableTable_12 extends _i1.SmartFake
    implements _i3.$PodcastTableTable {
  _Fake$PodcastTableTable_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$PodcastUpdateTableTable_13 extends _i1.SmartFake
    implements _i3.$PodcastUpdateTableTable {
  _Fake$PodcastUpdateTableTable_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$PodcastEpisodeTableTable_14 extends _i1.SmartFake
    implements _i3.$PodcastEpisodeTableTable {
  _Fake$PodcastEpisodeTableTable_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$DownloadedPodcastEpisodeTableTable_15 extends _i1.SmartFake
    implements _i3.$DownloadedPodcastEpisodeTableTable {
  _Fake$DownloadedPodcastEpisodeTableTable_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _Fake$DownloadTableTable_16 extends _i1.SmartFake
    implements _i3.$DownloadTableTable {
  _Fake$DownloadTableTable_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$PlayerStateTableTable_17 extends _i1.SmartFake
    implements _i3.$PlayerStateTableTable {
  _Fake$PlayerStateTableTable_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIndex_18 extends _i1.SmartFake implements _i2.Index {
  _FakeIndex_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedDatabase_19 extends _i1.SmartFake
    implements _i2.GeneratedDatabase {
  _FakeGeneratedDatabase_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_20 extends _i1.SmartFake
    implements _i2.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryUpdateRules_21 extends _i1.SmartFake
    implements _i2.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_22 extends _i1.SmartFake
    implements _i2.DatabaseConnection {
  _FakeDatabaseConnection_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_23 extends _i1.SmartFake implements _i2.QueryExecutor {
  _FakeQueryExecutor_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_24 extends _i1.SmartFake
    implements _i4.StreamQueryStore {
  _FakeStreamQueryStore_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_25 extends _i1.SmartFake
    implements _i2.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrator_26 extends _i1.SmartFake implements _i2.Migrator {
  _FakeMigrator_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_27<T> extends _i1.SmartFake implements _i5.Future<T> {
  _FakeFuture_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_28<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.InsertStatement<T1, D1> {
  _FakeInsertStatement_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_29<T extends _i2.Table, D> extends _i1.SmartFake
    implements _i2.UpdateStatement<T, D> {
  _FakeUpdateStatement_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_30<T1 extends _i2.HasResultSet, D>
    extends _i1.SmartFake
    implements _i2.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_30(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_31<FirstT extends _i2.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i2.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_31(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_32<Row> extends _i1.SmartFake
    implements _i2.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_32(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_33<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_33(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_34<T> extends _i1.SmartFake implements _i2.Selectable<T> {
  _FakeSelectable_34(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_35 extends _i1.SmartFake
    implements _i2.GenerationContext {
  _FakeGenerationContext_35(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Database].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabase extends _i1.Mock implements _i3.Database {
  MockDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion =>
      (super.noSuchMethod(Invocation.getter(#schemaVersion), returnValue: 0)
          as int);

  @override
  _i2.MigrationStrategy get migration =>
      (super.noSuchMethod(
            Invocation.getter(#migration),
            returnValue: _FakeMigrationStrategy_0(
              this,
              Invocation.getter(#migration),
            ),
          )
          as _i2.MigrationStrategy);

  @override
  _i3.$DatabaseManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _Fake$DatabaseManager_1(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i3.$DatabaseManager);

  @override
  _i3.$ArtistTableTable get artistTable =>
      (super.noSuchMethod(
            Invocation.getter(#artistTable),
            returnValue: _Fake$ArtistTableTable_2(
              this,
              Invocation.getter(#artistTable),
            ),
          )
          as _i3.$ArtistTableTable);

  @override
  _i3.$AlbumTableTable get albumTable =>
      (super.noSuchMethod(
            Invocation.getter(#albumTable),
            returnValue: _Fake$AlbumTableTable_3(
              this,
              Invocation.getter(#albumTable),
            ),
          )
          as _i3.$AlbumTableTable);

  @override
  _i3.$AlbumArtTableTable get albumArtTable =>
      (super.noSuchMethod(
            Invocation.getter(#albumArtTable),
            returnValue: _Fake$AlbumArtTableTable_4(
              this,
              Invocation.getter(#albumArtTable),
            ),
          )
          as _i3.$AlbumArtTableTable);

  @override
  _i3.$GenreTableTable get genreTable =>
      (super.noSuchMethod(
            Invocation.getter(#genreTable),
            returnValue: _Fake$GenreTableTable_5(
              this,
              Invocation.getter(#genreTable),
            ),
          )
          as _i3.$GenreTableTable);

  @override
  _i3.$TrackTableTable get trackTable =>
      (super.noSuchMethod(
            Invocation.getter(#trackTable),
            returnValue: _Fake$TrackTableTable_6(
              this,
              Invocation.getter(#trackTable),
            ),
          )
          as _i3.$TrackTableTable);

  @override
  _i3.$PlaylistTableTable get playlistTable =>
      (super.noSuchMethod(
            Invocation.getter(#playlistTable),
            returnValue: _Fake$PlaylistTableTable_7(
              this,
              Invocation.getter(#playlistTable),
            ),
          )
          as _i3.$PlaylistTableTable);

  @override
  _i3.$PlaylistTrackTableTable get playlistTrackTable =>
      (super.noSuchMethod(
            Invocation.getter(#playlistTrackTable),
            returnValue: _Fake$PlaylistTrackTableTable_8(
              this,
              Invocation.getter(#playlistTrackTable),
            ),
          )
          as _i3.$PlaylistTrackTableTable);

  @override
  _i3.$LikedTrackTableTable get likedTrackTable =>
      (super.noSuchMethod(
            Invocation.getter(#likedTrackTable),
            returnValue: _Fake$LikedTrackTableTable_9(
              this,
              Invocation.getter(#likedTrackTable),
            ),
          )
          as _i3.$LikedTrackTableTable);

  @override
  _i3.$StarredStationTableTable get starredStationTable =>
      (super.noSuchMethod(
            Invocation.getter(#starredStationTable),
            returnValue: _Fake$StarredStationTableTable_10(
              this,
              Invocation.getter(#starredStationTable),
            ),
          )
          as _i3.$StarredStationTableTable);

  @override
  _i3.$FavoriteRadioTagTableTable get favoriteRadioTagTable =>
      (super.noSuchMethod(
            Invocation.getter(#favoriteRadioTagTable),
            returnValue: _Fake$FavoriteRadioTagTableTable_11(
              this,
              Invocation.getter(#favoriteRadioTagTable),
            ),
          )
          as _i3.$FavoriteRadioTagTableTable);

  @override
  _i3.$PodcastTableTable get podcastTable =>
      (super.noSuchMethod(
            Invocation.getter(#podcastTable),
            returnValue: _Fake$PodcastTableTable_12(
              this,
              Invocation.getter(#podcastTable),
            ),
          )
          as _i3.$PodcastTableTable);

  @override
  _i3.$PodcastUpdateTableTable get podcastUpdateTable =>
      (super.noSuchMethod(
            Invocation.getter(#podcastUpdateTable),
            returnValue: _Fake$PodcastUpdateTableTable_13(
              this,
              Invocation.getter(#podcastUpdateTable),
            ),
          )
          as _i3.$PodcastUpdateTableTable);

  @override
  _i3.$PodcastEpisodeTableTable get podcastEpisodeTable =>
      (super.noSuchMethod(
            Invocation.getter(#podcastEpisodeTable),
            returnValue: _Fake$PodcastEpisodeTableTable_14(
              this,
              Invocation.getter(#podcastEpisodeTable),
            ),
          )
          as _i3.$PodcastEpisodeTableTable);

  @override
  _i3.$DownloadedPodcastEpisodeTableTable get downloadedPodcastEpisodeTable =>
      (super.noSuchMethod(
            Invocation.getter(#downloadedPodcastEpisodeTable),
            returnValue: _Fake$DownloadedPodcastEpisodeTableTable_15(
              this,
              Invocation.getter(#downloadedPodcastEpisodeTable),
            ),
          )
          as _i3.$DownloadedPodcastEpisodeTableTable);

  @override
  _i3.$DownloadTableTable get downloadTable =>
      (super.noSuchMethod(
            Invocation.getter(#downloadTable),
            returnValue: _Fake$DownloadTableTable_16(
              this,
              Invocation.getter(#downloadTable),
            ),
          )
          as _i3.$DownloadTableTable);

  @override
  _i3.$PlayerStateTableTable get playerStateTable =>
      (super.noSuchMethod(
            Invocation.getter(#playerStateTable),
            returnValue: _Fake$PlayerStateTableTable_17(
              this,
              Invocation.getter(#playerStateTable),
            ),
          )
          as _i3.$PlayerStateTableTable);

  @override
  _i2.Index get podcastEpisodeContentUrl =>
      (super.noSuchMethod(
            Invocation.getter(#podcastEpisodeContentUrl),
            returnValue: _FakeIndex_18(
              this,
              Invocation.getter(#podcastEpisodeContentUrl),
            ),
          )
          as _i2.Index);

  @override
  Iterable<_i2.TableInfo<_i2.Table, Object?>> get allTables =>
      (super.noSuchMethod(
            Invocation.getter(#allTables),
            returnValue: <_i2.TableInfo<_i2.Table, Object?>>[],
          )
          as Iterable<_i2.TableInfo<_i2.Table, Object?>>);

  @override
  List<_i2.DatabaseSchemaEntity> get allSchemaEntities =>
      (super.noSuchMethod(
            Invocation.getter(#allSchemaEntities),
            returnValue: <_i2.DatabaseSchemaEntity>[],
          )
          as List<_i2.DatabaseSchemaEntity>);

  @override
  _i2.GeneratedDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeGeneratedDatabase_19(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i2.GeneratedDatabase);

  @override
  _i2.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_20(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i2.DriftDatabaseOptions);

  @override
  _i2.StreamQueryUpdateRules get streamUpdateRules =>
      (super.noSuchMethod(
            Invocation.getter(#streamUpdateRules),
            returnValue: _FakeStreamQueryUpdateRules_21(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
          )
          as _i2.StreamQueryUpdateRules);

  @override
  _i2.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_22(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i2.DatabaseConnection);

  @override
  _i2.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i6.dummyValue<_i2.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i2.SqlTypes);

  @override
  _i2.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_23(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i2.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_24(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i4.StreamQueryStore);

  @override
  _i2.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_25(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i2.DatabaseConnectionUser);

  @override
  _i5.Future<void> reclaimDiskSpace() =>
      (super.noSuchMethod(
            Invocation.method(#reclaimDiskSpace, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i2.Migrator createMigrator() =>
      (super.noSuchMethod(
            Invocation.method(#createMigrator, []),
            returnValue: _FakeMigrator_26(
              this,
              Invocation.method(#createMigrator, []),
            ),
          )
          as _i2.Migrator);

  @override
  _i5.Future<void> beforeOpen(
    _i2.QueryExecutor? executor,
    _i2.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#beforeOpen, [executor, details]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Ret> computeWithDatabase<Ret, DB extends _i2.GeneratedDatabase>({
    required _i5.FutureOr<Ret> Function(DB)? computation,
    required DB Function(_i2.DatabaseConnection)? connect,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#computeWithDatabase, [], {
              #computation: computation,
              #connect: connect,
            }),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<Ret>(
                    this,
                    Invocation.method(#computeWithDatabase, [], {
                      #computation: computation,
                      #connect: connect,
                    }),
                  ),
                  (Ret v) => _i5.Future<Ret>.value(v),
                ) ??
                _FakeFuture_27<Ret>(
                  this,
                  Invocation.method(#computeWithDatabase, [], {
                    #computation: computation,
                    #connect: connect,
                  }),
                ),
          )
          as _i5.Future<Ret>);

  @override
  _i5.Stream<T> createStream<T extends Object>(
    _i4.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i5.Stream<T>.empty(),
          )
          as _i5.Stream<T>);

  @override
  T alias<T, D>(_i2.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i6.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i2.TableInfo<_i2.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i2.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Stream<Set<_i2.TableUpdate>> tableUpdates([
    _i2.TableUpdateQuery? query = const _i2.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i5.Stream<Set<_i2.TableUpdate>>.empty(),
          )
          as _i5.Stream<Set<_i2.TableUpdate>>);

  @override
  _i5.Future<T> doWhenOpened<T>(
    _i5.FutureOr<T> Function(_i2.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_27<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i5.Future<T>);

  @override
  _i2.InsertStatement<T, D> into<T extends _i2.Table, D>(
    _i2.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_28<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i2.InsertStatement<T, D>);

  @override
  _i2.UpdateStatement<Tbl, R> update<Tbl extends _i2.Table, R>(
    _i2.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_29<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i2.UpdateStatement<Tbl, R>);

  @override
  _i2.SimpleSelectStatement<T, R> select<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_30<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i2.SimpleSelectStatement<T, R>);

  @override
  _i2.JoinedSelectStatement<T, R> selectOnly<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_31<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i2.JoinedSelectStatement<T, R>);

  @override
  _i2.BaseSelectStatement<_i2.TypedResult> selectExpressions(
    Iterable<_i2.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_32<_i2.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i2.BaseSelectStatement<_i2.TypedResult>);

  @override
  _i2.DeleteStatement<T, D> delete<T extends _i2.Table, D>(
    _i2.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_33<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i2.DeleteStatement<T, D>);

  @override
  _i5.Future<int> customUpdate(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> customInsert(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i2.QueryRow>> customWriteReturning(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i5.Future<List<_i2.QueryRow>>.value(<_i2.QueryRow>[]),
          )
          as _i5.Future<List<_i2.QueryRow>>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelect(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_34<_i2.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i2.Selectable<_i2.QueryRow>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelectQuery(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_34<_i2.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i2.Selectable<_i2.QueryRow>);

  @override
  _i5.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T> transaction<T>(
    _i5.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_27<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<T> exclusively<T>(_i5.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_27<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<void> batch(_i5.FutureOr<void> Function(_i2.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T> runWithInterceptor<T>(
    _i5.Future<T> Function()? action, {
    required _i2.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_27<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i2.GenerationContext $write(
    _i2.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_35(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  _i2.GenerationContext $writeInsertable(
    _i2.TableInfo<_i2.Table, dynamic>? table,
    _i2.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_35(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i2.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);
}
