// Mocks generated by Mockito 5.4.6 from annotations
// in musicpod/test/subscribed_podcasts_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter_it/flutter_it.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:musicpod/common/data/audio.dart' as _i8;
import 'package:musicpod/podcasts/data/podcast_episode_filter.dart' as _i6;
import 'package:musicpod/podcasts/data/podcast_short_info.dart' as _i9;
import 'package:musicpod/podcasts/manager/podcast_manager.dart' as _i4;
import 'package:podcast_search/podcast_search.dart' as _i5;
import 'package:safe_change_notifier/safe_change_notifier.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCommand_0<TParam, TResult> extends _i1.SmartFake
    implements _i2.Command<TParam, TResult> {
  _FakeCommand_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSafeValueNotifier_1<T> extends _i1.SmartFake
    implements _i3.SafeValueNotifier<T> {
  _FakeSafeValueNotifier_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PodcastManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockPodcastManager extends _i1.Mock implements _i4.PodcastManager {
  MockPodcastManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Command<({_i5.SearchProvider searchProvider}), void>
  get initSearchCommand =>
      (super.noSuchMethod(
            Invocation.getter(#initSearchCommand),
            returnValue:
                _FakeCommand_0<({_i5.SearchProvider searchProvider}), void>(
                  this,
                  Invocation.getter(#initSearchCommand),
                ),
          )
          as _i2.Command<({_i5.SearchProvider searchProvider}), void>);

  @override
  _i3.SafeValueNotifier<bool> get updatesOnly =>
      (super.noSuchMethod(
            Invocation.getter(#updatesOnly),
            returnValue: _FakeSafeValueNotifier_1<bool>(
              this,
              Invocation.getter(#updatesOnly),
            ),
          )
          as _i3.SafeValueNotifier<bool>);

  @override
  _i3.SafeValueNotifier<bool> get downloadsOnly =>
      (super.noSuchMethod(
            Invocation.getter(#downloadsOnly),
            returnValue: _FakeSafeValueNotifier_1<bool>(
              this,
              Invocation.getter(#downloadsOnly),
            ),
          )
          as _i3.SafeValueNotifier<bool>);

  @override
  _i3.SafeValueNotifier<bool> get showSearch =>
      (super.noSuchMethod(
            Invocation.getter(#showSearch),
            returnValue: _FakeSafeValueNotifier_1<bool>(
              this,
              Invocation.getter(#showSearch),
            ),
          )
          as _i3.SafeValueNotifier<bool>);

  @override
  _i3.SafeValueNotifier<String?> get searchQuery =>
      (super.noSuchMethod(
            Invocation.getter(#searchQuery),
            returnValue: _FakeSafeValueNotifier_1<String?>(
              this,
              Invocation.getter(#searchQuery),
            ),
          )
          as _i3.SafeValueNotifier<String?>);

  @override
  _i3.SafeValueNotifier<_i6.PodcastEpisodeFilter> get filter =>
      (super.noSuchMethod(
            Invocation.getter(#filter),
            returnValue: _FakeSafeValueNotifier_1<_i6.PodcastEpisodeFilter>(
              this,
              Invocation.getter(#filter),
            ),
          )
          as _i3.SafeValueNotifier<_i6.PodcastEpisodeFilter>);

  @override
  _i2.Command<void, void> get wipeCommand =>
      (super.noSuchMethod(
            Invocation.getter(#wipeCommand),
            returnValue: _FakeCommand_0<void, void>(
              this,
              Invocation.getter(#wipeCommand),
            ),
          )
          as _i2.Command<void, void>);

  @override
  Set<String> get feedsWithDownloads =>
      (super.noSuchMethod(
            Invocation.getter(#feedsWithDownloads),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  void setUpdatesOnly(bool? value) => super.noSuchMethod(
    Invocation.method(#setUpdatesOnly, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setDownloadsOnly(bool? value) => super.noSuchMethod(
    Invocation.method(#setDownloadsOnly, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleDownloadsOnly() => super.noSuchMethod(
    Invocation.method(#toggleDownloadsOnly, []),
    returnValueForMissingStub: null,
  );

  @override
  void toggleShowSearch() => super.noSuchMethod(
    Invocation.method(#toggleShowSearch, []),
    returnValueForMissingStub: null,
  );

  @override
  void setSearchQuery(String? value) => super.noSuchMethod(
    Invocation.method(#setSearchQuery, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setFilter() => super.noSuchMethod(
    Invocation.method(#setFilter, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> updateAudioDuration(_i8.Audio? audio) =>
      (super.noSuchMethod(
            Invocation.method(#updateAudioDuration, [audio]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> togglePodcastSubscription({required String? feedUrl}) =>
      (super.noSuchMethod(
            Invocation.method(#togglePodcastSubscription, [], {
              #feedUrl: feedUrl,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Set<String>> getSubscribedPodcasts() =>
      (super.noSuchMethod(
            Invocation.method(#getSubscribedPodcasts, []),
            returnValue: _i7.Future<Set<String>>.value(<String>{}),
          )
          as _i7.Future<Set<String>>);

  @override
  _i7.Future<void> loadDownloads() =>
      (super.noSuchMethod(
            Invocation.method(#loadDownloads, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i9.PodcastShortInfo?> getPodcastShortInfo(String? feedUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getPodcastShortInfo, [feedUrl]),
            returnValue: _i7.Future<_i9.PodcastShortInfo?>.value(),
          )
          as _i7.Future<_i9.PodcastShortInfo?>);
}
